repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: trailing-whitespace
        exclude: ./.bumpversion
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.25.0
    exclude: ^docs/
    hooks:
      - id: yapf
        exclude: ^docs/
  - repo: git@github.com:coldnight/pre-commit-pylint.git
    rev: v0.0.3
    hooks:
      - id: pylint-score-limit
        exclude: ^docs/
        args:
          - --limit=8.0
          - --rcfile=./.pylintrc
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.650
    hooks:
      - id: mypy
        exclude: ^docs/
